apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube2py
  namespace: mateapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kube2py
  template:
    metadata:
      labels:
        app: kube2py
    spec:
      containers:
      - name: kube2py
        image: ikulyk404/kube2py:1.2.0
        ports:
        - containerPort: 8080
        env:
        - name: EXTERNAL_ENDPOINT
          value: "http://httpbin-api.mateapp.svc.cluster.local"
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
